apiVersion: v1
kind: Pod
metadata:
  name: example
  labels:
    run: spring-animals
spec:
  containers:
  - name: animals
    image: supergiantkir/animals:bear
    ports:
        - containerPort: 80
    volumeMounts:
    - name: example-storage
      mountPath: /data/data
  - name: springapp
    image: yanivomc/spring-music:latest
    ports:
        - containerPort: 8080
    volumeMounts:
    - name: example-storage
      mountPath: /app/data
  volumes:
  - name: example-storage
    emptyDir: {}
